### ISSUE TITLE
requirements.txt 里面缺少了SnowNLP依赖

### ISSUE THREAD

**Issue by zh-h** [shispt/weibo_sentiment#1]
``` shell
Traceback (most recent call last):
  File "weibo_sentiment/main.py", line 24, in <module>
    from weibo_sentiment import (
  File "/home/www/weibo_sentiment/weibo_sentiment/weibo_model.py", line 10, in <module>
    from snownlp import SnowNLP
ImportError: No module named snownlp

```

**Comment by shipengtaov** [comment]
#3
