### ISSUE TITLE
SnowNLP读取文件内存出错

### ISSUE THREAD

**Issue by zh-h** [shispt/weibo_sentiment#2]
``` shell
 * Running on http://127.0.0.1:8001/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "weibo_sentiment/main.py", line 24, in <module>
    from weibo_sentiment import (
  File "/home/www/weibo_sentiment/weibo_sentiment/weibo_model.py", line 10, in <module>
    from snownlp import SnowNLP
  File "/usr/local/lib/python2.7/dist-packages/snownlp/__init__.py", line 5, in <module>
    from . import seg
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/__init__.py", line 12, in <module>
    segger.load(data_path, True)
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/seg.py", line 23, in load
    self.segger.load(fname, iszip)
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/y09_2047.py", line 51, in load
    data = f.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 313, in _read
    self._add_read_data( uncompress )
  File "/usr/lib/python2.7/gzip.py", line 331, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError
```

**Comment by zh-h** [comment]
应该`"/usr/local/lib/python2.7/dist-packages/snownlp/seg/y09_2047.py", line 51, in load`

`data = f.read()`

这里需要按行读取

**Comment by shipengtaov** [comment]
这个 issue 可以提到 snownlp 哈

**Comment by zh-h** [comment]
@shispt 为什么按行读取然后连接起来的时候还是会出现编码错误，python的编码问题弄得我好苦恼。

**Comment by zh-h** [comment]
@shispt 看来主要是我内存不够用
